version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`codereview.mhirth.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend
    networks:
      - app_network
      - traefik_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=false"  # No need to expose backend via Traefik
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  traefik_network:
    external: true  # Use the existing Traefik network
